modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "extendedclouds"
version = "${version}"
displayName = "Extended Clouds"
authors = "notequalalpha"
description = '''
Makes clouds render further out.
'''
#logoFile = ""

[[dependencies.extendedclouds]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extendedclouds]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"